spring.application.name=Perfumeria
spring.datasource.url=${APP_DATABASE_URL:jdbc:mysql://localhost:3306/perfumeria?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${APP_DB_USERNAME:root}
spring.datasource.password=${APP_DATABASE_PASSWORD:facu}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8080}
spring.web.cors.allowed-origins=*